### ISSUE TITLE
Can't sync specific repository

### ISSUE THREAD

**Issue by pyama86** [actions/actions-sync#23]
Hi!
Thank you for always providing excellent service.
I got this error when I was syncing.

```
% go run . sync --cache-dir ./tmp --destination-token $GHE_TOKEN --destination-url https://ours.ghe.address --repo-name peter-evans/create-pull-request:example/create-pull-request
fetching * refs for peter-evans/create-pull-request ...
syncing `exampe/create-pull-request`
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x12f25f7]

goroutine 1 [running]:
github.com/go-git/go-git/v5/plumbing/protocol/packp.(*ReportStatus).Error(0x0, 0xc0000bc000, 0x168d470)
        /Users/pyama/src/github.com/actions/actions-sync/vendor/github.com/go-git/go-git/v5/plumbing/protocol/packp/report_status.go:31 +0x37
github.com/go-git/go-git/v5.(*Remote).PushContext(0xc0000c8ca8, 0x168f350, 0xc0000bc000, 0xc0003303c0, 0x0, 0x0)
        /Users/pyama/src/github.com/actions/actions-sync/vendor/github.com/go-git/go-git/v5/remote.go:189 +0x825
github.com/actions/actions-sync/src.syncWithCachedRepository(0x168f350, 0xc0000bc000, 0xc000523c78, 0xc000278000, 0xc0001936b0, 0x27, 0x168e0a0, 0x199ebd0, 0x0, 0x0)
        /Users/pyama/src/github.com/actions/actions-sync/src/push.go:206 +0x2ef
github.com/actions/actions-sync/src.PushWithGitImpl(0x168f350, 0xc0000bc000, 0xc000523c78, 0x7ffeefbfee92, 0x43, 0xc000196280, 0x168e0a0, 0x199ebd0, 0x8, 0xc0000de090)
        /Users/pyama/src/github.com/actions/actions-sync/src/push.go:110 +0x2d4
github.com/actions/actions-sync/src.PushManyWithGitImpl(0x168f350, 0xc0000bc000, 0xc005013c78, 0xc000593f30, 0x1, 0x1, 0xc000196280, 0x168e0a0, 0x199ebd0, 0x199ebd0, ...)
        /Users/pyama/src/github.com/actions/actions-sync/src/push.go:81 +0xb4
github.com/actions/actions-sync/src.Push(0x168f350, 0xc0000bc000, 0xc0005ddc78, 0x0, 0x0)
        /Users/pyama/src/github.com/actions/actions-sync/src/push.go:76 +0x16d
github.com/actions/actions-sync/src.Sync(0x168f350, 0xc0000bc000, 0x1970360, 0x0, 0x0)
        /Users/pyama/src/github.com/actions/actions-sync/src/sync.go:33 +0x16a
github.com/actions/actions-sync/cmd.glob..func4(0x1969ea0, 0xc0001a0200, 0x0, 0x8)
        /Users/pyama/src/github.com/actions/actions-sync/cmd/root.go:77 +0x96
github.com/spf13/cobra.(*Command).execute(0x1969ea0, 0xc0001a0100, 0x8, 0x8, 0x1969ea0, 0xc0001a0100)
        /Users/pyama/src/github.com/actions/actions-sync/vendor/github.com/spf13/cobra/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1969420, 0x1969ea0, 0x1, 0x1)
        /Users/pyama/src/github.com/actions/actions-sync/vendor/github.com/spf13/cobra/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/pyama/src/github.com/actions/actions-sync/vendor/github.com/spf13/cobra/command.go:887
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /Users/pyama/src/github.com/actions/actions-sync/vendor/github.com/spf13/cobra/command.go:880
github.com/actions/actions-sync/cmd.Execute(0x168f350, 0xc0000bc000, 0xc00018bf78, 0x1007a85)
        /Users/pyama/src/github.com/actions/actions-sync/cmd/root.go:98 +0x1b8
main.main()
        /Users/pyama/src/github.com/actions/actions-sync/main.go:13 +0x3d
exit status 2
```

I think that [peter-evans/create-pull-request](https://github.com/peter-evans/create-pull-request)  has a some problem but I don't resolve problem.

Please tell me why this problem occurs.

**Comment by ajaykn** [comment]
@pyama86  Apologies for the delay in response. Are you still seeing this issue ??

**Comment by pyama86** [comment]
@ajaykn thank you for your responcse.
I haven't used it.

thanks.
